### ISSUE TITLE
A question about USB

### ISSUE THREAD

**Issue by tucomel** [seven-of-eleven/designare-z390-opencore-efi#55]
Dude, I have the same configuration as you, same mobo same CPU same vga.
I already did the usbports and Im using the 0.76 version of usbinjectall.kext, everything is working flawsly but
i would like to know if there is any possibility to power-off the computer's USB/USB-c ports as soon as it goes into sleep mode, I have an nvme drive that heats up a lot even when the computer is in sleep mode, others devices such as keyboard or mouse is fine, but this drive isnt :( 
Thanks in advance

**Comment by baughmann** [comment]
You might try checking “Put drives to sleep” or something like that in the Power settings

**Comment by tucomel** [comment]
> You might try checking “Put drives to sleep” or something like that in the Power settings

This is my default setting for this option, didnt dit the trick , sad :(

**Comment by Neolo** [comment]
My USB (all of them at the same time) get randomly shut off after a week of uptime, sometimes a few days. This problem persists very long across all versions.

**Comment by ou2s** [comment]
Did you try to use the NVMEfix.kext ?

**Comment by seven-of-eleven** [comment]
@tucomel Not sure if you've solved this? I know it is recommended to replace USBInjectall.kext [after installation](https://dortania.github.io/OpenCore-Post-Install/usb/). Most would suggest you complete port mapping b/f installing the OS now as it has become harder to port map since macOS 11.3.

I suggest you try the USB mapping kext provided or create your own following the guide. Hopefully that will solve the issue for you. Let me know how you make out.
