### ISSUE TITLE
Question about personality keys used in USBPorts.kext

### ISSUE THREAD

**Issue by JonMcL** [seven-of-eleven/designare-z390-opencore-efi#61]
I'm attempting to improve my USB situation. I've been using my own version of USBPorts.kext, generated with trial-and-error using Hackintool, but it's far from perfect and I don't think Thunderbolt is working correctly.

When reviewing this repo's USBPorts.kext file I noticed that the IOKitPersonalities use iMacPro19,1 even though PlatformInfo info is iMac19,1. 

https://github.com/baughmann/designaire-z390-intel-i9-9900k-opencore/blob/1fcca8f9fb662fe127b2efa6b363940270faf98b/EFI/OC/Kexts/USBPorts.kext/Contents/Info.plist#L25
https://github.com/baughmann/designaire-z390-intel-i9-9900k-opencore/blob/1fcca8f9fb662fe127b2efa6b363940270faf98b/EFI/OC/Kexts/USBPorts.kext/Contents/Info.plist#L212

a. Typo and the keys of "personalities" don't really matter?
b. It's important that they use iMacPro19,1 instead of iMac19,1 for _reasons_?
c. None of the above?

**Comment by seven-of-eleven** [comment]
Hi @JonMcL I think you're right about the key values. My understanding from creating my own USB map was they needed to match the SMBIOS of you computer. I think the "newer" method being used [USBToolbox](https://github.com/USBToolBox/kext) avoids this as it states

>Override any built-in Apple USB maps attaching based on SMBIOS and controller name

but it wasn't used for this kext. As such they should be iMac19,1 and **not** iMacPro19,1.  I'll look into this a bit more to see if I can include 2 personalities (MacPro7,1 and iMac19,1) in the USBPort.kext, otherwise I'll update and rename the old USBPorts.kext as an optional download for those continuing to use iMac19,1.

Thanks for this.

**Comment by seven-of-eleven** [comment]
New USBPorts.kext included in the latest EFI should resolve this issue. Thanks.
