### ISSUE TITLE
Upgraded to 13.3, Wifi + ethernet port stopped working

### ISSUE THREAD

**Issue by arashster** [seven-of-eleven/designare-z390-opencore-efi#75]
After upgrading to 13.3, the Wifi (Fenvi T919) and bottom Ethernet port stopped working.
Using the no-bt-and-wifi config.plist.

**Comment by seven-of-eleven** [comment]
@arashster I've experienced the same thing. There seems to be a change in 13.3 release that wasn't present in the betas. People smarter than me are investigating it so hopefully we'll have a solution soon. You can disable AppleVTD for the time being if you don't need thunderbolt. Otherwise one of the ethernet ports should be functional (at least it is on my system). I'll continue to review and update here when the issue has been fixed.

**Comment by seven-of-eleven** [comment]
@arashster it seems CaseySJ has a patch to re-enable [wifi and ethernet](https://github.com/CaseySJ/Ventura-AppleVTD-Patch).  I've applied it to my computer and everything seems to be working well again. I'll update the repo with it later today. If interested you can check out the patch theory [here](https://www.tonymacx86.com/threads/success-gigabyte-designare-z390-thunderbolt-3-i7-9700k-amd-rx-580.316533/post-2365883).

**Comment by seven-of-eleven** [comment]
@arashster Patches have been applied and new release provided.
Thanks.
