### ISSUE TITLE
Thunderbolt Devices not Connecting

### ISSUE THREAD

**Issue by fvlasie** [seven-of-eleven/designare-z390-opencore-efi#79]
**Describe the bug**
My Presonus Quantum does not connect over thunderbolt.

**Expected behavior**
My Presonus Quantum should connect.

**Hardware Specifications (please complete the following information):**
 - CPU: Intel Core i9 9900k
 - GPU: AMD Radeon VII
 - Motherboard: Designaire Z390
 - Storage: Samsung Pro 990 APFS

**Additional context**
Thanks for posting your solution on github! My Presonus Quantum used to connect in Big Sur with a previous EFI made based on tonymacx86. I was hoping your EFI might help since I have not been able to get it working. Thank you!

**Comment by seven-of-eleven** [comment]
i'm not familiar enough with your hardware and I don't use thunderbolt regularly. I tested my EFI with one device I borrowed and it worked. Do you have other thunderbolt devices that you can test? Otherwise I would suggest you reach out on TonyMacx86 CaseySJ [Gigabyte Designare Z390 build](https://www.tonymacx86.com/threads/success-gigabyte-designare-z390-thunderbolt-3-i7-9700k-amd-rx-580.316533/). You may find more people there using thunderbolt that could help trouble shoot. It's hard when I don't have the hardware.

Best.

**Comment by fvlasie** [comment]
Thank you for your reply! I found help on tonymacx86, it turned out to be BIOS -> Thunderbolt -> Thunderbolt Boot Support ->  Boot Once.
